
name: 'Slack notification'
description: 'Create a post notification into Slack'
author: 'William Penagos'

branding:
  icon: 'check-circle'  
  color: 'green'

inputs:
  channel:
    description: 'Slack channel'
    required: true
  USER_ID:
    description: 'user ID'
    required: false
  title:
    description: 'Title'
    required: false
  message:
    description: 'Message for slack'
    required: true
  footer:
    description: 'Footer Message for slack'
    required: false
  status:
    description: 'Job status'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'