name: Testing PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: ./
        with:
          # TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          CHANNEL: 'asdsa23'
          # USER_ID: ${{env.USER_ID}}
          # TITLE: 'Testing slack command'
          # MESSAGE: 'Testing slack command'