name: Testing PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        if: always()
        with:
          status: ${{ job.status }}
          title: '{workflow} has {status_message}'
          message: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo_name}>'
          footer: 'Linked Repo <{repo_url}|{repo_name}>'
          notify_when: 'failure'
          mention_users: 'DJBCZ3T9C,DHS0U04TF'
          mention_users_when: 'failure,warnings'